language: ruby
rvm:
  - 2.0.0

matrix:
  allow_failures:
    - rvm: rbx-19mode

services:
  - redis

script:
- CODECLIMATE_REPO_TOKEN=f0884115cadbe82b33756e38a9cd32d5129304746a17126d6c7da02e7a69910a bundle exec rake 

notifications:
  email:
    - justin@jgrubbs.net

gemfile:
  - Gemfile


